server:
  port: 5051

spring:
  application:
    name: server-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/2DMore/sistema-academia.git
          search-paths: config-data
          default-label: development
